services:
  app:
    build:
      context: .
      target: runner
    env_file: .env
    ports:
      - "3000:3000"

  test:
    build:
      context: .
      target: test
    env_file: .env
    volumes:
      - .:/app
      - test_node_modules:/app/node_modules

volumes:
  test_node_modules:
